version: "3.9"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./src
    working_dir: /var/www/
    volumes:
      - ./src/:/var/www
    networks:
      - service-order-payments

  dborderpayment:
    image: mariadb:10.5-focal
    environment:
      MYSQL_DATABASE: db_micro_orders_payments
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    volumes:
      - data:/var/lib/mysql
    networks:
      - service-order-payments

  nginx:
    image: nginx:latest
    ports:
      - 8001:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/service-order-payments.conf:/etc/nginx/conf.d/default.conf
    networks:
      - service-order-payments

networks:
  service-order-payments:
    driver: bridge

volumes:
  data:
