version: "3.9"

networks:
  service-user:
    driver: bridge

services:
  app:
    build: ./src
    networks:
      - service-user

  dbuser:
    image: mariadb:10.5-focal
    env_file: ./src/.env
    volumes:
      - data:/var/lib/mysql
    networks:
      - service-user

  nginx:
    image: nginx:alpine
    ports:
      - "4002:80"
    volumes:
      - ./docker/nginx/service-user.conf:/etc/nginx/conf.d/default.conf
    networks:
      - service-user

volumes:
  data:
