version: "3.9"

services:
  app:
    build: ./src
    networks:
      - nodejs-app

  nginx:
    image: nginx:alpine
    ports:
      - "4000:80"
    volumes:
      - ./docker/nginx/api-gateway.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nodejs-app

networks:
  nodejs-app:
    driver: bridge
