version: "3.9"

networks:
  service-media:
    driver: bridge

services:
  app:
    build: ./src
    networks:
      - service-media

  dbmedia:
    image: mariadb:10.5-focal
    env_file: ./src/.env
    volumes:
      - data:/var/lib/mysql
    networks:
      - service-media

  nginx:
    image: nginx:alpine
    ports:
      - "4001:80"
    volumes:
      - ./docker/nginx/service-media.conf:/etc/nginx/conf.d/default.conf
    networks:
      - service-media

volumes:
  data:
