version: "3.9"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./src
    working_dir: /var/www/
    volumes:
      - ./src/:/var/www
    networks:
      - service-course

  dbcourse:
    image: mariadb:10.5-focal
    environment:
      MYSQL_DATABASE: db_micro_courses
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    volumes:
      - data:/var/lib/mysql
    networks:
      - service-course

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/service-course.conf:/etc/nginx/conf.d/default.conf
    networks:
      - service-course

networks:
  service-course:
    driver: bridge

volumes:
  data:
